---
- name: Monitor Kafka queue
  hosts: all
  sources:
    - name: AAP 2.5 Event Stream
      ansible.eda.webhook:

  rules:
    - name: Forward job_id and execute playbook. 
      condition: event.payload.job_id is defined
      action:
        run_job_template:
          name: "Test"
